### ISSUE TITLE
Add License Declaration

### ISSUE THREAD

**Issue by datapharmer** [taoduh/TestDataBundles#1]
Hi, would you be willing to declare what license this code is available for use under (MIT, BSD 3, GPL, etc)? Thanks!

**Comment by taoduh** [comment]
I added an MIT license.  This framework needs plenty of work as I documented.  I myself have been working on a much less generic framework because I wasn't sure doing all the work on this one would result in the time savings I initially hoped for.  But it might for the right project.  Good luck.
